### ISSUE TITLE
Define live-reload API

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/live-reload#1]
This is a discussion about live-reloads API and uses.

I'm guessing it would be best if we made this a SystemJS-like extension, but made it integrate nicely with steal-tools:
## System based names

```
> system-live-reload --port 8012 --config ./path/to/config.js --main main/module
```

```
// config.js
require("system-live-reload", function(){
  // rest of your config
  System.config({
    liveReload: 8012
  })
})
```

```
// package.json
{
  "system": {
    "configDependencies": ["system-live-reload"].
    "liveReload": 8012
  }
}
```
## steal-tools based API

If we wanted steal-tools to be able to provide this:

```
> steal-tools live-reload --port 8012 --config ./path/to/config.js --main main/module
```

**Comment by justinbmeyer** [comment]
@whitecolor's config:

```
config.watchalive.front = {
    options: {
        port: 7000,
        debug: true,
        base: __dirname,
        skip: ['bower_components/*'],
        middleware: [function(req, res){

        }],
        routes: [
            {'/': '/web/index.html'},
            {'/steal/*': '/bower_components/steal/*'},
            {'/mobile': '/mobile/index.html'},
            {'/chrome': '/chrome/index.html'},
            {'/dist/:dest': '/:dest/index.dist.html'},
            // routing for site sections /reader, /library, /details/:id ...
            {path: '^/[\\w\\d-]+(/[\\w\\d-]+)?$', regexp: 'i', target: '/web/index.html'}
        ],
        proxies: [
            {context: '/api', port: 4000}
        ]

    }
}
```

**Comment by justinbmeyer** [comment]
There's some cleanup that would have to happen in a CanJS app:

```
require("system-live-reload", function(onreload){
  // rest of your config
  System.config({
    liveReload: 8012
  });
  onreload(function(){
    can.app.restart()
  })
})
```

**Comment by justinbmeyer** [comment]
Considerations:
- Ideally, you could tag certain modules as having side-effects and always re-execute them.  For instance, a module that actually touches the DOM:

```
import can from "can"
import tmpl from "templ.stache!"

$("body").html(tmpl({}))

exports var undoLiveSideEffects = function(){
  $("body").empty()
};
```
- all parents of modules with this flag would have to be re-executed.
- System.delete then System.define with the new code would be fastest.

**Comment by whitecolor** [comment]
First, you should decide what live reload you want to impelement, possible options: 

1) Olny page reload when a source file(s) do change (`js/views/styles/etc`)
2) Hot replacement of styles (quite easy to implement) when using style tag for styles (for css, I would not recomment to use `less/css` on client slide, as it more costly in any scenario, I think preprocessor styles should be get ready on server side)
2) Hot replacement of code modules (`js/views/etc`) - replacing System.js changed modules without full page reload, can be impemented with `System.delete/define/import`, - there is need in more complicated logic on the client, including some work with dependency graph, `watchalive` now supports it, and it seems ti works not without issues but quite well.


What files are you going to watch for changes? Possible options:
1) All files that match a certain patter passed in config.
2) Only server files served to client (so you need to handle hosting for this), `watchalive` does this.

**Comment by matthewp** [comment]
Here's the beginning of the discussion surrounding this: https://gitter.im/stealjs/steal?at=54e294603def54753031e630

**Comment by matthewp** [comment]
So we need both a way to undo side effects and a way to call a reload function on modules.  For now what I have is:

``` js
// This is called when modules are being dismantled to clear out any side effects.
exports.liveReloadTeardown = function(){
  // Can return a promise
  return Promise.resolve().then( ...
};

// This is called after all modules have been re-imported. 
// This is where you re-render if you need to.
exports.onLiveReload = function(){

};
```

Not married to either name.  Both do need to be exports though.

**Comment by wclr** [comment]
I dont think that thre is a reason to stress much on side effects. just `beforeReload`, `afterReload` hooks (or events) would be fine.

**Comment by matthewp** [comment]
@whitecolor Those names aren't too bad, thanks.  I should have been more specific though, the hook I called `liveReloadTeardown` is **only** called when that module gets destroyed.  Whereas `onLiveReload` gets called every time a reload happen, regardless of whether that module was involved.

So while I do like the symmetry of `before` and `after` it makes it sound like they are the same types of hooks but they are not.

But it is better than my initial names :)  Getting closer...

**Comment by matthewp** [comment]
How about `beforeDestroy` and `afterReload`?  My only concern is clashing with a module's own exported names for normal functionality.

**Comment by wclr** [comment]
Actually I don't like much the idea that modules should have any kind of such exports really. Because for example this code will also be packed in production and it is not needed there. Maybe your implementation demands it.

**Comment by matthewp** [comment]
It's not very much code though. For example an `afterReload` will most likely look like this:

``` js
exports.afterReload = function(){
  render();
};
```

And this will probably only be in the `System.main` and no where else. For apps you probably won't need `beforeDestroy` but rarely. So code bloat isn't an issue here.

**Comment by matthewp** [comment]
So after talking yesterday about how to enhance the ability to observe a reload happen and looking into webpack's implementation I think it makes sense to add the ability to observe specific packages.  We still need to define the API as an export hook, otherwise there will be dangling callbacks.  I would propose something like:

## onReloadCycle

``` js
export function onReloadCycle(reload) {

  // Observe the complete reload cycle, called after complete.
  reload(function(){
    render();
  });

  // Observe a specific module. Returns the modules value after reload.
  reload("other", function(other) {
    window.other = other;
  });

  // Observe all reloaded modules, gets called for each
  reload("*", function(moduleName, moduleValue){

  });

  // Called when this module gets deleted.
  reload.dispose(function() {
    $("#site").remove();
  });

  // Called when another module gets deleted.
  reload.dispose("other", function() {
    // Do cleanup related to ./other ?
  });
};
```

(note that this is the complete api, replacing `beforeDestroy` and `afterReload`)

**Comment by matthewp** [comment]
You will also be able to import `live-reload` and use the same API.  the difference is that if you import it, the callbacks will leak so you don't want to do it within the code. This is useful for demo pages. You might do:

``` html
<script src="node_modules/steal/steal.js">

  import reload from "live-reload";
  import stache from "can/view/stache/stache";
  import $ from "jquery";

  // Called after every reload cycle.
  reload(function(){
    render();
  });

  var renderer = stache("<hello-world></hello-world>");

  function render() {
    $("#app").html(renderer());
  }

  // Do the initial render
  render();

</script>
<div id="app"></div>
```

**Comment by matthewp** [comment]
Ok, I figured out a way to make it so that you don't need the export.  You can just do:

``` js
import reload from "live-reload";


reload("app/router", function(router){
  router.start();
});

reload.dispose(function(){
  $("#app").empty();
});

```

**Comment by matthewp** [comment]
This is done.
