### ISSUE TITLE
Re-initialize can.routes on reload()

### ISSUE THREAD

**Issue by marshallswain** [stealjs/live-reload#9]
My attrs in can.route don't get rebound after a live-reload.  I'm doing the below to make it work:

``` js
// Routes
can.route('', {page:'dashboard'});
can.route(':page');

import reload from 'live-reload';
reload(function(){
  var attrs = can.route.attr();
  can.route.attr({}, true);
  can.route.attr(attrs, true);
});

// ...

can.route.ready();
```

Is there a better way to make this happen?

**Comment by matthewp** [comment]
My guess is that you won't need to do this if you avoid calling can.route.ready() every time, only call that the initial time.

Alternative you could use `reload.dispose` to destroy the routes (I'm not sure how to do this).

**Comment by matthewp** [comment]
Going to close this for now, let me know if this doesn't answer your question and I'll reopen.
